In [1]:
import pandas as pd

In [2]:

df = pd.read_csv('JC-201901-citibike-tripdata.csv')
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [3]:
df1 = pd.read_csv('JC-201902-citibike-tripdata.csv')
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,142,2019-02-01 15:35:02.0820,2019-02-01 15:37:24.1360,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29677,Subscriber,1963,1
1,223,2019-02-01 17:00:46.8900,2019-02-01 17:04:30.5500,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,26234,Subscriber,1992,2
2,106,2019-02-01 17:08:01.3260,2019-02-01 17:09:47.4400,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29588,Subscriber,1960,1
3,370,2019-02-01 17:09:31.2100,2019-02-01 17:15:41.6550,3183,Exchange Place,40.716247,-74.033459,3211,Newark Ave,40.721525,-74.046305,29250,Subscriber,1976,1
4,315,2019-02-01 17:19:53.2490,2019-02-01 17:25:09.1400,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,29586,Subscriber,1980,1

In [7]:
df1.count()

tripduration               18565
starttime                  18565
stoptime                   18565
start station id           18565
start station name         18565
start station latitude     18565
start station longitude    18565
end station id             18565
end station name           18565
end station latitude       18565
end station longitude      18565
bikeid                     18565
usertype                   18565
birth year                 18565
gender                     18565
dtype: int64

In [4]:
df2 = pd.read_csv('JC-201903-citibike-tripdata.csv')
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,306,2019-03-01 06:47:08.2110,2019-03-01 06:52:14.7150,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26272,Subscriber,1989,1
1,123,2019-03-01 07:30:53.0220,2019-03-01 07:32:56.7770,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26192,Subscriber,1966,1
2,328,2019-03-01 08:18:30.4030,2019-03-01 08:23:59.0590,3183,Exchange Place,40.716247,-74.033459,3213,Van Vorst Park,40.718489,-74.047727,26226,Subscriber,1971,2
3,95,2019-03-01 11:04:47.2020,2019-03-01 11:06:22.8130,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,26204,Subscriber,1985,1
4,169,2019-03-01 11:51:29.4170,2019-03-01 11:54:19.2120,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,29449,Subscriber,1971,1

In [5]:
df3 = pd.read_csv('JC-201904-citibike-tripdata.csv')
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,107,2019-04-01 07:48:04.7540,2019-04-01 07:49:52.3590,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29536,Subscriber,1966,1
1,493,2019-04-01 12:41:09.6540,2019-04-01 12:49:23.0290,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,26191,Customer,1990,1
2,512,2019-04-01 14:27:07.9400,2019-04-01 14:35:40.9370,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1987,2
3,196,2019-04-01 15:07:38.1510,2019-04-01 15:10:54.6260,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,26220,Subscriber,1989,1
4,463,2019-04-01 16:19:24.6940,2019-04-01 16:27:08.6450,3183,Exchange Place,40.716247,-74.033459,3273,Manila & 1st,40.721651,-74.042884,26228,Subscriber,1995,1

In [8]:
df2.count()

tripduration               23606
starttime                  23606
stoptime                   23606
start station id           23606
start station name         23606
start station latitude     23606
start station longitude    23606
end station id             23606
end station name           23606
end station latitude       23606
end station longitude      23606
bikeid                     23606
usertype                   23606
birth year                 23606
gender                     23606
dtype: int64

In [6]:
df4 = pd.read_csv('JC-201905-citibike-tripdata.csv')
df4.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2

In [9]:
df10 = pd.read_csv('data-cZMp8.csv')
df10.head()

,Date,Trips over the past 24-hours (midnight to 11:59pm),Miles traveled today (midnight to 11:59 pm),Total Annual Members (All Time),24-Hour Passes Purchased (midnight to 11:59 pm),3-Day Passes Purchased (midnight to 11:59 pm)
0,1/1/19,22145,44131,297823,2429,49
1,1/2/19,38249,58975,297908,1062,36
2,1/3/19,42181,62500,297976,969,31
3,1/4/19,44420,65739,298017,1173,33
4,1/5/19,17636,24326,298048,462,8

In [10]:
df10.count()

Date                                                  90
Trips over the past 24-hours (midnight to 11:59pm)    90
Miles traveled today (midnight to 11:59 pm)           90
Total Annual Members (All Time)                       90
24-Hour Passes Purchased (midnight to 11:59 pm)       90
3-Day Passes Purchased (midnight to 11:59 pm)         90
dtype: int64

In [11]:
citibike_2019 = pd.concat([df,df1, df2, df3, df4])
citibike_2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
5,737,2019-01-01 12:56:53.2040,2019-01-01 13:09:11.0400,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,29447,Subscriber,1993,1
6,917,2019-01-01 13:03:44.7760,2019-01-01 13:19:02.7690,3183,Exchange Place,40.716247,-74.033459,3277,Communipaw & Berry Lane,40.714358,-74.066611,29299,Subscriber,1986,1
7,3248,2019-01-01 13:12:03.1280,2019-01-01 14:06:12.0400,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,40.744319,-74.043991,29495,Subscriber,1992,1
8,3168,2019-01-01 13:13:12.0450,2019-01-01 14:06:00.4110,3183,Exchange Place,40.716247,-74.033459,3196,Riverview Park,40.744319,-74.043991,26312,Customer,1969,0
9,353,2019-01-01 17:07:44.6670,2019-01-01 17:13:38.2640,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,26212,Subscriber,1994,1
10,503,2019-01-01 17:34:50.9580,2019-01-01 17:43:14.3190,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29661,Customer,1992,1
11,285,2019-01-01 18:06:03.1680,2019-01-01 18:10:48.5380,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29544,Subscriber,1990,1
12,229,2019-01-01 20:05:04.5760,2019-01-01 20:08:53.8630,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29307,Subscriber,1996,1
13,211,2019-01-01 21:04:58.8810,2019-01-01 21:08:30.5600,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29217,Subscriber,1993,1
14,111,2019-01-01 21:52:09.2980,2019-01-01 21:54:00.4550,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29453,Subscriber,1987,1
15,663,2019-01-01 21:54:27.9360,2019-01-01 22:05:31.8800,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29286,Subscriber,1987,1
16,451,2019-01-02 00:08:06.5510,2019-01-02 00:15:38.0940,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29453,Subscriber,1960,1
17,742,2019-01-02 07:17:22.2050,2019-01-02 07:29:45.1610,3183,Exchange Place,40.716247,-74.033459,3270,Jersey & 6th St,40.725289,-74.045572,29608,Subscriber,1977,1
18,121,2019-01-02 07:55:53.5040,2019-01-02 07:57:54.9410,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29122,Subscriber,1966,1
19,284,2019-01-02 08:09:38.7570,2019-01-02 08:14:23.6940,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,26202,Subscriber,1986,1
20,120,2019-01-02 08:18:36.9570,2019-01-02 08:20:37.9440,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29602,Subscriber,1975,2
21,75,2019-01-02 08:25:25.9610,2019-01-02 08:26:41.4140,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29228,Subscriber,1975,1
22,113,2019-01-02 08:47:54.6750,2019-01-02 08:49:47.9970,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,26278,Subscriber,1969,1
23,187,2019-01-02 10:39:26.6940,2019-01-02 10:42:34.6680,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,26288,Subscriber,1982,1
24,259,2019-01-02 10:57:36.4500,2019-01-02 11:01:55.7620,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29641,Subscriber,1984,1
25,969,2019-01-02 11:45:40.3390,2019-01-02 12:01:49.4380,3183,Exchange Place,40.716247,-74.033459,3207,Oakland Ave,40.737604,-74.052478,29252,Subscriber,1981,1
26,355,2019-01-02 12:12:43.7790,2019-01-02 12:18:39.1990,3183,Exchange Place,40.716247,-74.033459,3272,Jersey & 3rd,40.723332,-74.045953,29484,Subscriber,1988,1
27,288,2019-01-02 12:22:12.8260,2019-01-02 12:27:01.5450,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,29293,Subscriber,1981,2
28,2602,2019-01-02 12:27:14.6360,2019-01-02 13:10:37.2240,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,29286,Customer,1969,0
29,1360,2019-01-02 12:32:56.9960,2019-01-02 12:55:37.7920,3183,Exchange Place,40.716247,-74.033459,3183,Exchange Place,40.716247,-74.033459,26208,Customer,1971,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36105,115,2019-05-31 23:00:41.7730,2019-05-31 23:02:37.7010,3275,Columbus Drive,40.718355,-74.038914,3681,Grand St,40.715178,-74.037683,29640,Subscriber,1979,1
36106,277,2019-05-31 23:03:52.1510,2019-05-31 23:08:29.2790,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,26262,Subscriber,1984,1
36107,350,2019-05-31 23:04:30.7370,2019-05-31 23:10:20.9500,3194,McGinley Square,40.725340,-74.067622,3191,Union St,40.718211,-74.083639,29497,Subscriber,1988,1
36108,392,2019-05-31 23:05:54.0600,2019-05-31 23:12:26.2200,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,29463,Subscriber,1990,1
36109,360,2019-05-31 23:06:34.9240,2019-05-31 23:12:35.3080,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29679,Subscriber,1983,2
36110,483,2019-05-31 23:09:45.2640,2019-05-31 23:17:48.8110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,29614,Subscriber,1990,1
36111,218,2019-05-31 23:20:12.9000,2019-05-31 23:23:51.7010,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26268,Subscriber,1964,1
36112,209,2019-05-31 23:20:54.9570,2019-05-31 23:24:23.9860,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,29286,Subscriber,1958,1
36113,172,2019-05-31 23:21:12.0370,2019-05-31 23:24:05.0000,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,29121,Subscriber,1990,1
36114,487,2019-05-31 23:23:18.6710,2019-05-31 23:31:26.6640,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29304,Subscriber,1969,0
36115,679,2019-05-31 23:25:36.4860,2019-05-31 23:36:56.3050,3194,McGinley Square,40.725340,-74.067622,3191,Union St,40.718211,-74.083639,26224,Subscriber,1962,1
36116,515,2019-05-31 23:27:17.9620,2019-05-31 23:35:52.9950,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29570,Subscriber,1990,2
36117,798,2019-05-31 23:28:14.8690,2019-05-31 23:41:33.1750,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,26211,Customer,1990,1
36118,370,2019-05-31 23:29:30.0540,2019-05-31 23:35:40.3240,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,26300,Subscriber,1986,1
36119,1757,2019-05-31 23:31:21.5580,2019-06-01 00:00:38.6070,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29654,Customer,1985,1
36120,341,2019-05-31 23:31:24.9430,2019-05-31 23:37:05.9980,3186,Grove St PATH,40.719586,-74.043117,3278,Monmouth and 6th,40.725685,-74.048790,29221,Subscriber,1974,1
36121,221,2019-05-31 23:31:26.0290,2019-05-31 23:35:07.7590,3186,Grove St PATH,40.719586,-74.043117,3278,Monmouth and 6th,40.725685,-74.048790,29608,Subscriber,1970,1
36122,162,2019-05-31 23:32:22.1550,2019-05-31 23:35:04.3670,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26260,Subscriber,1994,1
36123,166,2019-05-31 23:33:24.2660,2019-05-31 23:36:11.2210,3184,Paulus Hook,40.714145,-74.033552,3267,Morris Canal,40.712419,-74.038526,29280,Subscriber,1968,1
36124,620,2019-05-31 23:33:42.0130,2019-05-31 23:44:02.6220,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,26180,Customer,1969,0
36125,740,2019-05-31 23:34:08.2610,2019-05-31 23:46:29.0720,3639,Harborside,40.719252,-74.034234,3211,Newark Ave,40.721525,-74.046305,29652,Customer,1969,0
36126,431,2019-05-31 23:38:15.9200,2019-05-31 23:45:27.8610,3194,McGinley Square,40.725340,-74.067622,3193,Lincoln Park,40.724605,-74.078406,26250,Subscriber,1969,1
36127,1141,2019-05-31 23:41:44.3110,2019-06-01 00:00:46.1300,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
36128,128,2019-05-31 23:45:36.8750,2019-05-31 23:47:45.0740,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,29302,Subscriber,1971,1
36129,239,2019-05-31 23:47:20.1130,2019-05-31 23:51:19.7830,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,26260,Subscriber,1984,2
36130,792,2019-05-31 23:51:00.1170,2019-06-01 00:04:12.4530,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,26236,Customer,1991,1
36131,779,2019-05-31 23:51:22.7840,2019-06-01 00:04:22.3990,3186,Grove St PATH,40.719586,-74.043117,3214,Essex Light Rail,40.712774,-74.036486,29205,Customer,1991,2
36132,347,2019-05-31 23:55:38.3850,2019-06-01 00:01:26.2030,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26179,Subscriber,1989,2
36133,552,2019-05-31 23:56:11.9740,2019-06-01 00:05:24.8810,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29528,Subscriber,1992,1
36134,520,2019-05-31 23:56:25.0240,2019-06-01 00:05:05.4860,3192,Liberty Light Rail,40.711242,-74.055701,3277,Communipaw & Berry Lane,40.714358,-74.066611,29589,Subscriber,1984,2

In [14]:
citibike_2019.count()

tripduration               131038
starttime                  131038
stoptime                   131038
start station id           131038
start station name         131038
start station latitude     131038
start station longitude    131038
end station id             131038
end station name           131038
end station latitude       131038
end station longitude      131038
bikeid                     131038
usertype                   131038
birth year                 131038
gender                     131038
dtype: int64

In [13]:

# Export to csv
df10.to_csv("clean_data/clean_ridership_data_2019.csv")
citibike_2019.to_csv("clean_data/citibike_data_2019.csv")